name: CI Build

on: [push, workflow_dispatch]
permissions:
  contents: write
  packages: read


jobs:
  debug-build:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    with:
      build-config: Debug

  release-build:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    with:
      build-config: Release
