name: CI Build

on: [push, workflow_dispatch]
permissions:
  contents: write
  packages: read

env:
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  NUGET_MROESSLER_GITHUB_PWD: ${{ secrets.NUGET_READ }}

jobs:
  debug-build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      build-config: Debug

  release-build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      build-config: Release
