name: Publish API docs to wiki
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      NUGET_MROESSLER_GITHUB_PWD: ${{ secrets.NUGET_READ }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: "*/*.csproj"
      
      - name: Install npm packages
        run: npm install -g jsdoc-to-markdown 

      - name: Generate docs
        run: |
          dotnet build MRoessler.BlazorBottomSheet -p:BoShGenerateMdDocs=true 

      - uses: Andrew-Chen-Wang/github-wiki-action@1bbb4280446f9630e8e21a18012cbacf3b0f992e # v5.0.6
        with:
          path: docs
          disable-empty-commits: true
