name: Deploy sample WebAssembly app
env:
  PUBLISH_DIR: Sample.Wasm/bin/Release/net10.0/publish/wwwroot

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    env:
      DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      NUGET_MROESSLER_GITHUB_PWD: ${{ secrets.NUGET_READ }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: "*/*.csproj"

      - name: Publish app
        run: dotnet publish Sample.Wasm -c Release

      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@4583ede549773dabe1410c42e703d54cf52859ff # v1.1.0
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: /MRoessler.BlazorBottomSheet/

      - name: Rewrite JS module import paths
        run: bash .github/scripts/rewrite-js-module-paths.sh
        
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ${{ env.PUBLISH_DIR }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
